# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lab09' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lab09
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'

  target 'lab09Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'lab09UITests' do
    # Pods for testing
  end

end
